# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fBayes"
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ivan Acosta-Rubio"]
  s.date = "2013-03-05"
  s.description = "Naitve Bayes for Food Category classification"
  s.email = "ivan@bakedweb.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".DS_Store",
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "brainstorms.txt",
    "fBayes.gemspec",
    "lib/.DS_Store",
    "lib/data/.DS_Store",
    "lib/data/MyFoodapediaData/Food_Display_Table.xml",
    "lib/data/MyFoodapediaData/Foods_Needing_Condiments_Table.xml",
    "lib/data/MyFoodapediaData/lu_Condiment_Food_Table.xml",
    "lib/data/cdc/.DS_Store",
    "lib/data/cdc/classifier.rb",
    "lib/data/cdc/data.html",
    "lib/data/cdc/data/beverages",
    "lib/data/cdc/data/dairy",
    "lib/data/cdc/data/fruits_and_vegetables",
    "lib/data/cdc/data/grains",
    "lib/data/cdc/data/mixed_dishes",
    "lib/data/cdc/data/other_foods",
    "lib/data/cdc/data/protein_foods",
    "lib/data/cdc/data/water",
    "lib/data/cdc/ruby_parser.rb",
    "lib/data/internalTurnk/.DS_Store",
    "lib/data/internalTurnk/classifier.rb",
    "lib/data/internalTurnk/csv_to_data.rb",
    "lib/data/internalTurnk/data/Beverages",
    "lib/data/internalTurnk/data/Cereal",
    "lib/data/internalTurnk/data/Dairy",
    "lib/data/internalTurnk/data/Fast-foods",
    "lib/data/internalTurnk/data/Fats",
    "lib/data/internalTurnk/data/Fruits",
    "lib/data/internalTurnk/data/Grains",
    "lib/data/internalTurnk/data/Protein",
    "lib/data/internalTurnk/data/Unknown",
    "lib/data/internalTurnk/data/Vegetables",
    "lib/data/internalTurnk/results.csv",
    "lib/data/sr24/.DS_Store",
    "lib/data/sr24/FD_GROUP.csv",
    "lib/data/sr24/FD_GROUP.txt",
    "lib/data/sr24/FOOD_DES.csv",
    "lib/data/sr24/FOOD_DES.txt",
    "lib/data/sr24/classifier.rb",
    "lib/data/sr24/convert_to_csv.rb",
    "lib/data/sr24/csv_to_muchidata.rb",
    "lib/data/sr24/data/.DS_Store",
    "lib/data/sr24/data/baby-foods",
    "lib/data/sr24/data/baked-products",
    "lib/data/sr24/data/beef-products",
    "lib/data/sr24/data/beverages",
    "lib/data/sr24/data/breakfast-cereals",
    "lib/data/sr24/data/cereal-grains-and-pasta",
    "lib/data/sr24/data/dairy-and-egg-products",
    "lib/data/sr24/data/ethnic-foods",
    "lib/data/sr24/data/fast-foods",
    "lib/data/sr24/data/fats-and-oils",
    "lib/data/sr24/data/finfish-and-shellfish-products",
    "lib/data/sr24/data/fruits-and-fruit-juices",
    "lib/data/sr24/data/lamb",
    "lib/data/sr24/data/legumes-and-legume-products",
    "lib/data/sr24/data/meals",
    "lib/data/sr24/data/nut-and-seed-products",
    "lib/data/sr24/data/pork-products",
    "lib/data/sr24/data/poultry-products",
    "lib/data/sr24/data/restaurant-foods",
    "lib/data/sr24/data/sausages-and-luncheon-meats",
    "lib/data/sr24/data/snacks",
    "lib/data/sr24/data/soups",
    "lib/data/sr24/data/spices-and-herbs",
    "lib/data/sr24/data/sweets",
    "lib/data/sr24/data/vegetables-and-vegetable-products",
    "lib/data/sr24/rawData/.DS_Store",
    "lib/data/sr24/rawData/Dats_Src.pdf",
    "lib/data/sr24/rawData/sr24_doc.pdf",
    "lib/fBayes.rb",
    "lib/global_classifier.rb",
    "spec/accuracy_spec.rb",
    "spec/clasificador_spec.rb",
    "spec/fBayes_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/ivanacostarubio/fBayes"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Naive Bayes for Food Category classification"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<classifier>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<classifier>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<classifier>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

